name: app_cliente_ecoprint
description: Sistema Ecoprint
publish_to: 'none' 
version: 0.0.0-alpha.9

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter
  dependency_module:
    path: ../modulos/dependency_module

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true