name: ops_module
description: Modulo de OPS
publish_to: 'none'
version: 0.0.0-alpha.3
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  pdf: ^3.6.5
  printing: ^5.6.6
  flutter:
    sdk: flutter
  dependency_module:
    path: ../dependency_module

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
