name: decoder_upload_csv_web_package
description: Package responsavel pela decodificação dos arquivos csv em string
publish_to: 'none'
version: 1.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter
  dependency_module:
    path: ../../modulos/dependency_module

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: